# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('subject_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Bulletin_Board')),
            ],
        ),
    ]
