# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
