# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_reply_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin_board',
            name='secret_board',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulletin_board',
            name='secret_board_key',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
